baseURL = "https://blog.fundalytica.com/"
languageCode = "en-us"
title = "The Fundalytica Blog"
copyright = "© Fundalytica 2019 - ∞"

theme = "ananke"
publishdir = "/var/www/blog"

# googleAnalytics = ""

enableRobotsTXT = true

[sitemap]
    changefreq = "monthly"
    priority = 0.5
    filename = "sitemap.xml"

[menu]
  [[menu.main]]
    identifier = "posts"
    name = "Articles"
    url = "/posts"
    weight = 1
  [[menu.main]]
    identifier = "www"
    name = "fundalytica.com"
    url = "https://www.fundalytica.com"
    weight = 2

[params]
    favicon = "favicon.ico"
    featured_image = "/images/hero/fundalytica.jpg"
    show_reading_time = true
    post_content_classes = "avenir bg-near-white"
    instagram = "https://www.instagram.com/fundalytica/"
    medium = "https://medium.com/fundalytica/"
    # twitter = "https://twitter.com/fundalytica"
    rss = "https://blog.fundalytica.com/index.xml"

# https://github.com/tachyons-css/tachyons/blob/v4.7.0/src/_font-family.css
# https://github.com/tachyons-css/tachyons/blob/v4.7.0/src/_skins.css